Feat/3
memocode-dev/memocode_question_server pull request #4
Opened 2024-03-24 16:33 UTC by duswnsxnxn

2024-03-25 06:15 UTC, audgks5551 requested changes

2024-03-25 06:15 UTC, audgks5551 commented on src/main/java/dev/memocode/question_server/domain/question/repository/impl/QuestionRepositoryImpl.java
>                  .selectFrom(QQuestion.question)
findAllQuestion에서 태그를 가져오는 경우에 question만 가져오시고 tag의 경우에는 @OneToMany를 통해 넣으시는건 어떠신가요?

지금 로직이 복잡하지 않아도 되는데 많이 복잡합니다.

2024-03-25 06:15 UTC, audgks5551 commented on src/main/java/dev/memocode/question_server/domain/question/service/QuestionService.java
> +        return questionRepository.save(question).getId();
처음에 모든 태그를 entity로 가져오신 후에 question에서 연관관계를 통해 tag를 생성하거나 지우시면 좀 더 객체지향적으로 작성되고 코드의 양이나 가독성면에서도 좋을 것 같습니다

2024-03-25 06:15 UTC, audgks5551 commented on src/main/java/dev/memocode/question_server/domain/question/service/QuestionService.java
>      }
이 메서드를 usecase로 주시지 마시고 내부에서만 사용할 수 있게 해주시고 다른 메서드를 만드셔서 question dto가 반환될 수 있도록 해주세요 :)

2024-03-25 06:15 UTC, audgks5551 commented on src/main/java/dev/memocode/question_server/usecase/QuestionUseCase.java
> +    Question findQuestionById(UUID questionId);
예시로 QuestionDTO가 반환되야 합니다.
엔티티가 반환되지 않게 해주세요.

2024-04-09 15:09 UTC, audgks5551 requested changes
정말 수고하셨습니다
조금만 더 수정부탁드립니다 :)

2024-04-09 15:09 UTC, audgks5551 commented on src/main/java/dev/memocode/question_server/domain/question/entity/Question.java
> +
updateTags 함수만 만들어서 생성,수정,삭제가 모두 일어날 수 있도록 구현해주세요.
그리고 QuestionService에서 updateTags 함수만 불러서 tag를 생성,수정,삭제가 일어날 수 있게 해주시고
updateTags에서 파생된 함수들은 모두 private 처리하여 외부에서 접근하지 못하게 작성해주세요!

2024-04-09 16:13 UTC, duswnsxnxn commented on src/main/java/dev/memocode/question_server/domain/question/entity/Question.java
> +
네 알겠습니다!

2024-04-10 12:05 UTC, memocodee requested changes

2024-04-10 12:05 UTC, memocodee commented on src/main/java/dev/memocode/question_server/domain/question/entity/Question.java
> +
여기서 updateTags만을 이용해서 생성, 수정, 삭제가 일어날 수 있도록 구성해주세요!

2024-04-11 13:26 UTC, merged